# Generated by Django 4.2.5 on 2023-10-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='reference_code',
            field=models.CharField(max_length=255),
        ),
    ]
